import { ConversationState, updateConversationState } from "./context";
import { getKnowledgeResponse } from "./knowledge";
import { getEstimateResponse } from "./estimate";
import { getFallbackResponse } from "./fallback";
import { callPrimaryAI } from "./llm";
import { getAdvice } from "./recommendations";
import { getTriageResult } from "./triage"; // Import the new Triage AI

interface ChatbotResponse {
    response: string;
    newState: ConversationState;
}

export async function routeConversation(
    state: ConversationState,
    userQuery: string
): Promise<ChatbotResponse> {
    // 1. Get a rich understanding of the user's query using the Triage AI.
    const triage = await getTriageResult(userQuery);

    // 2. Update the conversation state with the new, structured information.
    let workingState = updateConversationState(state, {
        fullHistory: [{ role: "user", content: userQuery }],
        lastIntent: triage.intent,
        activeGoal: triage.intent, // Align active goal with the detected intent
        city: triage.entities.city || state.city, // Persist if already known
        lastMaterialMentioned: triage.entities.material || state.lastMaterialMentioned,
        roomType: triage.entities.roomType || state.roomType,
        userPriorities: triage.userPriorities,
    });

    let response: string;
    let adviceForAI: string | undefined = undefined;

    // 3. Route based on the AI-detected intent.
    switch (triage.intent) {
        case 'design_advice':
            const advice = getAdvice(workingState, userQuery);
            if (advice.hasAdvice) {
                adviceForAI = advice.adviceText;
            }
            break;

        case 'material_info':
            const knowledge = getKnowledgeResponse(workingState, userQuery);
            response = knowledge.answer;
            workingState = updateConversationState(workingState, knowledge.updatedState);
            break;

        case 'get_estimate':
            const estimate = getEstimateResponse(workingState, userQuery);
            response = estimate.answer;
            workingState = updateConversationState(workingState, estimate.updatedState);
            break;

        case 'confirm':
            response = "Theek hai, samajh gayi. Aage batayein.";
            break;

        case 'unknown':
        default:
            // If intent is unknown, let the main AI handle it. No special advice needed.
            break;
    }

    // 4. If a response has not been generated by a specific handler, call the primary AI.
    if (!response) {
        const aiResponse = await callPrimaryAI(workingState, adviceForAI);
        response = aiResponse.content;
    }

    // 5. Finalize state and return.
    workingState = updateConversationState(workingState, {
        fullHistory: [{ role: "assistant", content: response }],
    });

    return {
        response,
        newState: workingState,
    };
}
