// Placeholder-marked entries (Katihar, Madhepura, Kishanganj districts/cities and all blog posts)
// are structurally real but use generic copy — replace via the admin CMS once real
// photos/testimonials/local details are available for those areas.

export const districtsSeed = [
  {
    slug: "araria",
    name: "Araria",
    nameHi: "अरारिया",
    description:
      "JK Interior's home district and primary service zone, covering Forbesganj, Araria city, Jogbani, Narpatganj, Raniganj and Kursakanta.",
    heroImage: "/images/hero-interior.jpg",
    displayOrder: 1,
  },
  {
    slug: "purnia",
    name: "Purnia",
    nameHi: "पूर्णिया",
    description:
      "One of North Bihar's largest cities — JK Interior brings Forbesganj-quality craftsmanship to homes, offices and showrooms across Purnia.",
    heroImage: "/images/gallery-27.jpg",
    displayOrder: 2,
  },
  {
    slug: "supaul",
    name: "Supaul",
    nameHi: "सुपौल",
    description:
      "A fast-growing district for home improvement — JK Interior serves Supaul city, Tribeniganj and Chhatapur with false ceiling and interior design.",
    heroImage: "/images/gallery-29.jpg",
    displayOrder: 3,
  },
  {
    slug: "katihar",
    name: "Katihar",
    nameHi: "कटिहार",
    description:
      "JK Interior is extending its false ceiling and interior design services to Katihar district — placeholder district page, real project photos and local content to follow.",
    heroImage: "/images/gallery-30.jpg",
    displayOrder: 4,
  },
  {
    slug: "madhepura",
    name: "Madhepura",
    nameHi: "मधेपुरा",
    description:
      "JK Interior is extending its false ceiling and interior design services to Madhepura district — placeholder district page, real project photos and local content to follow.",
    heroImage: "/images/gallery-31.jpg",
    displayOrder: 5,
  },
  {
    slug: "kishanganj",
    name: "Kishanganj",
    nameHi: "किशनगंज",
    description:
      "JK Interior is extending its false ceiling and interior design services to Kishanganj district — placeholder district page, real project photos and local content to follow.",
    heroImage: "/images/gallery-3.jpg",
    displayOrder: 6,
  },
];

export const citiesSeed = [
  {
    slug: "forbesganj",
    name: "Forbesganj",
    nameHi: "फोर्बेसगंज",
    districtSlug: "araria",
    distanceFromHq: "Main Office",
    description:
      "JK Interior is headquartered in Forbesganj. We are the most trusted interior design and false ceiling contractor for homes, shops, and offices in Forbesganj, Araria.",
    uniqueContent:
      "Forbesganj is the heart of JK Interior's operations. As the primary base of our business, we serve every neighbourhood in Forbesganj with the fastest response time and most competitive pricing.",
    keywords: [
      "interior designer Forbesganj",
      "false ceiling contractor Forbesganj",
      "PVC ceiling Forbesganj",
      "gypsum ceiling Forbesganj",
    ],
    displayOrder: 1,
  },
  {
    slug: "araria-city",
    name: "Araria",
    nameHi: "अरारिया",
    districtSlug: "araria",
    distanceFromHq: "22 km from Forbesganj",
    description:
      "JK Interior provides premium false ceiling, PVC wall paneling, and interior design services in Araria. We are Araria district's top-rated interior contractor.",
    uniqueContent:
      "Araria is the district headquarters and a growing hub for modern interior design. JK Interior serves all areas of Araria city — from residential apartments to commercial showrooms and offices.",
    keywords: ["interior designer Araria", "false ceiling contractor Araria", "gypsum ceiling Araria"],
    displayOrder: 2,
  },
  {
    slug: "jogbani",
    name: "Jogbani",
    nameHi: "जोगबनी",
    districtSlug: "araria",
    distanceFromHq: "35 km from Forbesganj",
    description:
      "JK Interior provides modern interior design, false ceiling, PVC wall paneling and WPC louver installation services in Jogbani, Araria district.",
    uniqueContent:
      "Jogbani, located at the India–Nepal border, is a bustling commercial town with growing demand for modern interior design.",
    keywords: ["interior designer Jogbani", "false ceiling Jogbani", "PVC ceiling Jogbani Araria"],
    displayOrder: 3,
  },
  {
    slug: "narpatganj",
    name: "Narpatganj",
    nameHi: "नरपतगंज",
    districtSlug: "araria",
    distanceFromHq: "28 km from Forbesganj",
    description: "JK Interior provides expert false ceiling, PVC ceiling, gypsum ceiling and interior design services in Narpatganj, Araria district.",
    uniqueContent:
      "Narpatganj is one of the prominent blocks in Araria district, and JK Interior regularly serves its growing residential and commercial clients.",
    keywords: ["interior designer Narpatganj", "false ceiling Narpatganj"],
    displayOrder: 4,
  },
  {
    slug: "raniganj",
    name: "Raniganj",
    nameHi: "रानीगंज",
    districtSlug: "araria",
    distanceFromHq: "18 km from Forbesganj",
    description: "JK Interior serves Raniganj, Araria with modern interior design, false ceiling, PVC wall paneling and gypsum ceiling services at the best price.",
    uniqueContent:
      "Raniganj, a growing town in Araria district, is well within JK Interior's primary service zone — just 18 km from our Forbesganj office.",
    keywords: ["interior designer Raniganj", "false ceiling Raniganj Araria"],
    displayOrder: 5,
  },
  {
    slug: "kursakanta",
    name: "Kursakanta",
    nameHi: "कुर्साकाँटा",
    districtSlug: "araria",
    distanceFromHq: "32 km from Forbesganj",
    description: "JK Interior provides PVC false ceiling, gypsum ceiling, WPC wall panel and interior design services in Kursakanta, Araria district.",
    uniqueContent:
      "Kursakanta is a well-connected block in Araria district where JK Interior actively provides interior design and ceiling services.",
    keywords: ["interior designer Kursakanta", "false ceiling Kursakanta Araria"],
    displayOrder: 6,
  },
  {
    slug: "purnia-city",
    name: "Purnia",
    nameHi: "पूर्णिया",
    districtSlug: "purnia",
    distanceFromHq: "65 km from Forbesganj",
    description: "JK Interior serves Purnia with premium gypsum ceiling, PVC false ceiling, WPC wall panel and complete interior design solutions at competitive prices.",
    uniqueContent:
      "Purnia is one of North Bihar's largest cities, and JK Interior is proud to serve its residents and businesses with Forbesganj-quality craftsmanship.",
    keywords: ["interior designer Purnia", "false ceiling contractor Purnia"],
    displayOrder: 1,
  },
  {
    slug: "supaul-city",
    name: "Supaul",
    nameHi: "सुपौल",
    districtSlug: "supaul",
    distanceFromHq: "55 km from Forbesganj",
    description: "JK Interior offers false ceiling, PVC wall paneling, gypsum ceiling and interior design services in Supaul district, Bihar at affordable prices.",
    uniqueContent:
      "Supaul district has seen rapid growth in construction and home improvement projects, and JK Interior extends its services to Supaul city and surrounding areas.",
    keywords: ["interior designer Supaul", "false ceiling Supaul Bihar"],
    displayOrder: 1,
  },
  {
    slug: "tribeniganj",
    name: "Tribeniganj",
    nameHi: "त्रिवेणीगंज",
    districtSlug: "supaul",
    distanceFromHq: "48 km from Forbesganj",
    description: "JK Interior offers interior design, PVC ceiling, gypsum ceiling and wall paneling services in Tribeniganj, Supaul district at affordable prices.",
    uniqueContent:
      "Tribeniganj in Supaul district is an important commercial centre that JK Interior serves with dedicated interior design and ceiling solutions.",
    keywords: ["interior designer Tribeniganj", "false ceiling Tribeniganj Supaul"],
    displayOrder: 2,
  },
  {
    slug: "chhatapur",
    name: "Chhatapur",
    nameHi: "छतापुर",
    districtSlug: "supaul",
    distanceFromHq: "52 km from Forbesganj",
    description: "JK Interior provides false ceiling, PVC ceiling, gypsum ceiling and interior design services in Chhatapur, Supaul district at competitive prices.",
    uniqueContent:
      "Chhatapur in Supaul district is a growing town where JK Interior delivers modern interior design and false ceiling services.",
    keywords: ["interior designer Chhatapur", "false ceiling Chhatapur Supaul"],
    displayOrder: 3,
  },
  {
    slug: "katihar-city",
    name: "Katihar",
    nameHi: "कटिहार",
    districtSlug: "katihar",
    distanceFromHq: "95 km from Forbesganj",
    description: "JK Interior brings false ceiling, PVC/gypsum ceiling and complete interior design services to Katihar city — new service area.",
    uniqueContent:
      "Placeholder content — real Katihar project photos, pricing notes, and local landmarks to be added once the first projects there are completed.",
    keywords: ["interior designer Katihar", "false ceiling Katihar Bihar"],
    displayOrder: 1,
  },
  {
    slug: "madhepura-city",
    name: "Madhepura",
    nameHi: "मधेपुरा",
    districtSlug: "madhepura",
    distanceFromHq: "80 km from Forbesganj",
    description: "JK Interior brings false ceiling, PVC/gypsum ceiling and complete interior design services to Madhepura city — new service area.",
    uniqueContent:
      "Placeholder content — real Madhepura project photos, pricing notes, and local landmarks to be added once the first projects there are completed.",
    keywords: ["interior designer Madhepura", "false ceiling Madhepura Bihar"],
    displayOrder: 1,
  },
  {
    slug: "kishanganj-city",
    name: "Kishanganj",
    nameHi: "किशनगंज",
    districtSlug: "kishanganj",
    distanceFromHq: "70 km from Forbesganj",
    description: "JK Interior brings false ceiling, PVC/gypsum ceiling and complete interior design services to Kishanganj city — new service area.",
    uniqueContent:
      "Placeholder content — real Kishanganj project photos, pricing notes, and local landmarks to be added once the first projects there are completed.",
    keywords: ["interior designer Kishanganj", "false ceiling Kishanganj Bihar"],
    displayOrder: 1,
  },
];

export const servicesSeed = [
  {
    slug: "pvc-false-ceiling",
    name: "PVC False Ceiling",
    shortDescription: "100% waterproof, termite-proof PVC ceiling panels for kitchens, bathrooms, and any room.",
    overview:
      "PVC false ceiling is our most requested service — lightweight, fully waterproof panels that install fast and need almost no maintenance. It's the go-to choice for kitchens, bathrooms, balconies and budget-friendly full-home ceilings.",
    benefits: ["100% waterproof and termite-proof", "Low maintenance, wipes clean", "Fast installation, minimal dust", "Wide range of colors and designs"],
    applications: ["Kitchens", "Bathrooms", "Balconies", "Bedrooms", "Shops and showrooms"],
    materialsUsed: ["PVC panels", "GI channel framework", "LED cove lighting profiles"],
    installationProcess: [
      { step: "Site measurement", description: "Free on-site visit to measure the room and note electrical/plumbing points." },
      { step: "Framework installation", description: "GI channel grid is fixed to the ceiling slab." },
      { step: "Panel fixing", description: "PVC panels are cut to size and clipped into the framework." },
      { step: "Finishing", description: "Edge trims, cove lighting, and final cleaning." },
    ],
    priceRangeMin: 70,
    priceRangeMax: 140,
    priceUnit: "sq.ft",
    heroImage: "/images/pvc-ceiling.jpg",
    icon: "waves",
    displayOrder: 1,
  },
  {
    slug: "gypsum-false-ceiling",
    name: "Gypsum False Ceiling",
    shortDescription: "Elegant POP-style gypsum ceilings with cove lighting for living rooms and bedrooms.",
    overview:
      "Gypsum false ceiling delivers the smooth, paintable finish clients want for living rooms, bedrooms and drawing rooms, with room for cove lighting and multi-level POP designs.",
    benefits: ["Smooth, paintable finish", "Supports multi-level cove lighting designs", "Good fire resistance", "Wide design flexibility"],
    applications: ["Living rooms", "Bedrooms", "Drawing rooms", "Dry commercial spaces"],
    materialsUsed: ["Gypsum boards", "GI channel framework", "POP cornices", "LED cove lighting"],
    installationProcess: [
      { step: "Design consultation", description: "Choose a flat, cove, or multi-level design." },
      { step: "Framework installation", description: "GI channels are suspended from the slab." },
      { step: "Board fixing & jointing", description: "Gypsum boards are screwed on and joints are taped and finished." },
      { step: "Painting & lighting", description: "Primer, paint, and cove/LED lighting fixed." },
    ],
    priceRangeMin: 80,
    priceRangeMax: 150,
    priceUnit: "sq.ft",
    heroImage: "/images/gypsum-ceiling.jpg",
    icon: "sparkles",
    displayOrder: 2,
  },
  {
    slug: "wpc-wall-panel",
    name: "WPC Wall Panel",
    shortDescription: "Moisture-resistant wood-look wall panels for accent walls and TV units.",
    overview:
      "WPC (Wood Plastic Composite) wall panels give the warmth of wood with none of the termite or moisture risk — ideal for TV accent walls, headboard walls and full-room paneling.",
    benefits: ["Eco-friendly wood-look finish", "Moisture and termite resistant", "Easy to clean, long lasting", "Modern fluted and louver textures available"],
    applications: ["TV accent walls", "Bedroom headboard walls", "Office reception walls", "Full room paneling"],
    materialsUsed: ["WPC louver/fluted panels", "Aluminium clips", "Edge banding"],
    installationProcess: [
      { step: "Wall measurement", description: "Site visit to measure wall dimensions and check surface." },
      { step: "Batten framework", description: "Support battens fixed to the wall." },
      { step: "Panel installation", description: "WPC panels clipped and aligned edge to edge." },
      { step: "Finishing", description: "Trim, corners and cleaning." },
    ],
    priceRangeMin: 180,
    priceRangeMax: 450,
    priceUnit: "sq.ft",
    heroImage: "/images/wpc-louvers.jpg",
    icon: "layout-panel-left",
    displayOrder: 3,
  },
  {
    slug: "uv-marble-sheet",
    name: "UV Marble Sheet",
    shortDescription: "High-gloss, scratch-resistant marble-look sheets for walls and feature areas.",
    overview:
      "UV marble sheets replicate the high-gloss look of natural marble at a fraction of the cost and weight, and install without the mess of stone work.",
    benefits: ["High-gloss, hygienic surface", "Scratch and stain resistant", "Lightweight, dust-free installation", "Wide pattern range"],
    applications: ["Feature walls", "Kitchen backsplash", "Pooja room walls", "Reception areas"],
    materialsUsed: ["UV-coated marble sheets", "Adhesive/fixing system"],
    installationProcess: [
      { step: "Surface preparation", description: "Wall surface leveled and cleaned." },
      { step: "Sheet cutting", description: "Sheets cut to size for the wall/feature area." },
      { step: "Fixing", description: "Sheets fixed with adhesive and mechanical fasteners at joints." },
      { step: "Finishing", description: "Joint sealing and edge trims." },
    ],
    priceRangeMin: 50,
    priceRangeMax: 95,
    priceUnit: "sq.ft",
    heroImage: "/images/uv-marble.jpg",
    icon: "gem",
    displayOrder: 4,
  },
  {
    slug: "modular-tv-unit",
    name: "Modular TV Unit",
    shortDescription: "Custom-designed TV units with premium finish and integrated cable management.",
    overview:
      "A custom TV unit ties the whole living room together — we design around your wall size, TV dimensions and storage needs, with clean cable routing built in.",
    benefits: ["Custom sizing and finish", "Integrated cable management", "Storage + display combinations", "Matches ceiling and wall panel design"],
    applications: ["Living rooms", "Bedrooms", "Home theatres"],
    materialsUsed: ["Plywood/MDF carcass", "Laminate or veneer finish", "WPC/PVC accent panels"],
    installationProcess: [
      { step: "Design & 3D preview", description: "Unit designed to the wall and TV size, shared as a visual before approval." },
      { step: "Fabrication", description: "Unit fabricated in the workshop to spec." },
      { step: "On-site fixing", description: "Unit installed and leveled against the wall." },
      { step: "Final detailing", description: "Cable routing, lighting and hardware finished." },
    ],
    priceRangeMin: 15000,
    priceRangeMax: 60000,
    priceUnit: "unit",
    heroImage: "/images/tv-unit.jpg",
    icon: "tv",
    displayOrder: 5,
  },
  {
    slug: "complete-interior-design",
    name: "Complete Interior Design",
    shortDescription: "Full-home interior — ceiling, wall panels, TV unit and kitchen under one team and timeline.",
    overview:
      "For new homes and full renovations, we run ceiling, wall paneling, TV units and kitchen work as one coordinated project instead of separate contractors — one point of contact, one timeline, one warranty.",
    benefits: ["Single point of contact for the full project", "Coordinated timeline across all trades", "Consistent design language room to room", "One unified warranty"],
    applications: ["New homes", "Full home renovations", "Builder-floor fit-outs"],
    materialsUsed: ["Combination of PVC/gypsum/WPC/UV marble as designed"],
    installationProcess: [
      { step: "Requirement discussion", description: "Understand rooms, budget and style preference." },
      { step: "Design & quotation", description: "Room-by-room design and itemized quotation." },
      { step: "Execution", description: "Phased execution room by room with a shared project timeline." },
      { step: "Handover", description: "Final walkthrough, cleaning and warranty documentation." },
    ],
    priceRangeMin: 0,
    priceRangeMax: 0,
    priceUnit: "custom quote",
    heroImage: "/images/gallery-4.jpg",
    icon: "home",
    displayOrder: 6,
  },
  {
    slug: "bedroom-interior",
    name: "Bedroom Interior",
    shortDescription: "False ceiling, wardrobe, TV unit and lighting design for a complete bedroom makeover.",
    overview:
      "A bedroom interior package brings together ceiling design, wardrobe, TV/headboard wall and lighting into one cohesive room design.",
    benefits: ["Cohesive ceiling + wall + storage design", "Better use of room storage", "Ambient lighting design included"],
    applications: ["Master bedrooms", "Children's rooms", "Guest rooms"],
    materialsUsed: ["Gypsum/PVC ceiling", "Plywood wardrobes", "WPC/laminate accent walls"],
    installationProcess: [
      { step: "Room measurement", description: "Full room measured including wardrobe wall." },
      { step: "Design proposal", description: "Ceiling + wardrobe + accent wall design shared for approval." },
      { step: "Execution", description: "Ceiling first, then wardrobe and wall paneling." },
      { step: "Styling & handover", description: "Lighting fitted and final styling touches done." },
    ],
    priceRangeMin: 60,
    priceRangeMax: 180,
    priceUnit: "sq.ft",
    heroImage: "/images/gypsum1.jpg",
    icon: "bed",
    displayOrder: 7,
  },
  {
    slug: "kitchen-interior",
    name: "Kitchen Interior",
    shortDescription: "Waterproof ceiling and modular kitchen fit-out built for daily Indian kitchen use.",
    overview:
      "Kitchens need waterproof, heat-resistant materials — we pair PVC/UV-marble ceiling and backsplash work with modular cabinetry sized to your kitchen layout.",
    benefits: ["100% waterproof ceiling and backsplash options", "Layout-specific modular cabinetry", "Heat and stain resistant surfaces"],
    applications: ["Modular kitchens", "Kitchen ceilings", "Backsplash and counter cladding"],
    materialsUsed: ["PVC ceiling panels", "UV marble backsplash", "Marine plywood cabinetry"],
    installationProcess: [
      { step: "Layout measurement", description: "Kitchen layout and appliance points measured." },
      { step: "Design proposal", description: "Cabinet and ceiling layout proposed with material options." },
      { step: "Execution", description: "Ceiling and cabinetry installed in sequence." },
      { step: "Final fitting", description: "Hardware, backsplash and lighting completed." },
    ],
    priceRangeMin: 70,
    priceRangeMax: 200,
    priceUnit: "sq.ft",
    heroImage: "/images/pvc1.jpg",
    icon: "chef-hat",
    displayOrder: 8,
  },
  {
    slug: "office-interior",
    name: "Office Interior",
    shortDescription: "Grid ceiling, partitions and reception design built for daily commercial use.",
    overview:
      "Office fit-outs prioritize durability and quick turnaround — grid ceilings, glass/panel partitions and a reception feature wall that all hold up to daily foot traffic.",
    benefits: ["Commercial-grade, low-maintenance materials", "Acoustic ceiling options for meeting rooms", "Fast turnaround to limit business downtime"],
    applications: ["Reception areas", "Cabins and workstations", "Meeting rooms", "Retail showrooms"],
    materialsUsed: ["Grid/mineral fiber ceiling", "Glass and panel partitions", "WPC/laminate feature walls"],
    installationProcess: [
      { step: "Site survey", description: "Office layout, electrical and HVAC points surveyed." },
      { step: "Layout design", description: "Partition and ceiling layout proposed for approval." },
      { step: "Execution", description: "Work scheduled around business hours to limit disruption." },
      { step: "Handover", description: "Final inspection and snag-list clearance." },
    ],
    priceRangeMin: 45,
    priceRangeMax: 250,
    priceUnit: "sq.ft",
    heroImage: "/images/gallery-30.jpg",
    icon: "briefcase",
    displayOrder: 9,
  },
  {
    slug: "acp-exterior",
    name: "ACP Exterior",
    shortDescription: "Weather-resistant Aluminium Composite Panel cladding for building exteriors and shop fronts.",
    overview:
      "ACP cladding gives shop fronts and building exteriors a clean, modern look while standing up to Bihar's sun and monsoon — commonly used for storefronts, signage backgrounds and building facades.",
    benefits: ["Weatherproof, UV-stable finish", "Lightweight compared to stone/tile cladding", "Wide color and finish range"],
    applications: ["Shop fronts", "Building facades", "Signage backgrounds"],
    materialsUsed: ["ACP sheets", "Aluminium frame structure"],
    installationProcess: [
      { step: "Facade survey", description: "Exterior wall/frontage measured and surveyed." },
      { step: "Frame installation", description: "Aluminium support frame fixed to the facade." },
      { step: "Panel fixing", description: "ACP sheets cut and fixed to the frame." },
      { step: "Sealing", description: "Joints sealed for weatherproofing." },
    ],
    priceRangeMin: 150,
    priceRangeMax: 350,
    priceUnit: "sq.ft",
    heroImage: "/images/gallery-31.jpg",
    icon: "building-2",
    displayOrder: 10,
  },
  {
    slug: "louvers-panel",
    name: "Louvers Panel",
    shortDescription: "3D textured louver panels for trending feature walls and reception areas.",
    overview:
      "Louver panels add depth and a modern textured look to feature walls, reception backdrops and office lobbies — one of the most-requested trending designs right now.",
    benefits: ["Modern 3D textured look", "Available in wood-look and solid finishes", "Quick installation over existing walls"],
    applications: ["Feature walls", "Reception backdrops", "Office lobbies"],
    materialsUsed: ["WPC/PVC louver panels", "Aluminium support battens"],
    installationProcess: [
      { step: "Wall measurement", description: "Feature wall measured and surface checked." },
      { step: "Batten framework", description: "Support battens fixed at even spacing." },
      { step: "Louver fixing", description: "Louver panels clipped into place." },
      { step: "Finishing", description: "Edge trims and final cleaning." },
    ],
    priceRangeMin: 200,
    priceRangeMax: 500,
    priceUnit: "sq.ft",
    heroImage: "/images/wpc2.jpg",
    icon: "align-justify",
    displayOrder: 11,
  },
  {
    slug: "charcoal-panel",
    name: "Charcoal Panel",
    shortDescription: "Rich matte-finish charcoal wall panels for a bold, contemporary accent wall.",
    overview:
      "Charcoal panels bring a bold, matte, dark-toned finish to accent walls — a favorite for home theatres, bedroom headboard walls and premium office cabins.",
    benefits: ["Bold, contemporary matte finish", "Moisture resistant", "Pairs well with warm LED lighting"],
    applications: ["Home theatre walls", "Bedroom headboard walls", "Premium office cabins"],
    materialsUsed: ["Charcoal-finish WPC panels", "Aluminium clips"],
    installationProcess: [
      { step: "Wall measurement", description: "Accent wall measured and surface checked." },
      { step: "Batten framework", description: "Support battens fixed to the wall." },
      { step: "Panel fixing", description: "Charcoal panels clipped and aligned." },
      { step: "Finishing", description: "Edge trims and lighting integration." },
    ],
    priceRangeMin: 180,
    priceRangeMax: 400,
    priceUnit: "sq.ft",
    heroImage: "/images/gallery-3.jpg",
    icon: "square-stack",
    displayOrder: 12,
  },
];

export const projectsSeed = [
  {
    slug: "forbesganj-living-room-pvc-ceiling",
    title: "Forbesganj Living Room — PVC False Ceiling",
    serviceSlug: "pvc-false-ceiling",
    citySlug: "forbesganj",
    spaceType: "residential" as const,
    materialTags: ["pvc"],
    areaSqft: 220,
    materials: "PVC ceiling panels, LED cove lighting",
    timeline: "2 days",
    costRangeMin: 18000,
    costRangeMax: 26000,
    challenge: "Client wanted a waterproof ceiling that still looked premium, on a tight 3-day timeline before a family function.",
    solution: "Installed a cove-lit PVC ceiling with a two-tone panel layout, completed in 2 days with zero mess.",
    beforeImage: "/images/gallery-3.jpg",
    afterImage: "/images/pvc-ceiling.jpg",
    images: ["/images/pvc-ceiling.jpg", "/images/pvc1.jpg", "/images/pvc2.jpg"],
    customerName: "Rahul Kumar",
    customerReview: "JK Interior ने हमारे घर का PVC false ceiling बेहद खूबसूरती से लगाया। काम की quality और speed दोनों exceptional थी।",
    customerRating: 5,
    displayOrder: 1,
  },
  {
    slug: "araria-bedroom-gypsum-ceiling",
    title: "Araria Bedroom — Gypsum Ceiling with Cove Lighting",
    serviceSlug: "gypsum-false-ceiling",
    citySlug: "araria-city",
    spaceType: "residential" as const,
    materialTags: ["gypsum"],
    areaSqft: 180,
    materials: "Gypsum boards, POP cornice, LED cove",
    timeline: "3 days",
    costRangeMin: 22000,
    costRangeMax: 30000,
    challenge: "Client wanted a multi-level ceiling design without cracking issues common with local POP work.",
    solution: "Used a GI-channel gypsum board system with proper jointing to prevent cracks, finished with cove lighting.",
    beforeImage: "/images/gallery-4.jpg",
    afterImage: "/images/gypsum-ceiling.jpg",
    images: ["/images/gypsum-ceiling.jpg", "/images/gypsum1.jpg", "/images/gypsum2.jpg"],
    customerName: "Priya Sharma",
    customerReview: "Gypsum ceiling के लिए JK Interior को hire किया। Result देखकर neighbors भी impressed हो गए।",
    customerRating: 5,
    displayOrder: 2,
  },
  {
    slug: "purnia-tv-unit-wpc-panel",
    title: "Purnia Living Room — WPC Wall Panel & TV Unit",
    serviceSlug: "wpc-wall-panel",
    citySlug: "purnia-city",
    spaceType: "residential" as const,
    materialTags: ["wpc", "tv-unit"],
    areaSqft: 140,
    materials: "WPC louver panels, custom TV unit",
    timeline: "4 days",
    costRangeMin: 45000,
    costRangeMax: 65000,
    challenge: "Client wanted a wood-look accent wall without termite risk in a humid location near the river belt.",
    solution: "Installed moisture-resistant WPC louver panels with an integrated floating TV unit and cable management.",
    beforeImage: "/images/gallery-27.jpg",
    afterImage: "/images/wpc-louvers.jpg",
    images: ["/images/wpc-louvers.jpg", "/images/wpc1.jpg", "/images/tv-unit.jpg"],
    customerName: "Amit Singh",
    customerReview: "WPC wall paneling का काम बहुत अच्छा किया। Termite-proof और waterproof panels लगाए।",
    customerRating: 5,
    displayOrder: 3,
  },
  {
    slug: "supaul-office-grid-ceiling",
    title: "Supaul Office — Grid Ceiling & Partition",
    serviceSlug: "office-interior",
    citySlug: "supaul-city",
    spaceType: "office" as const,
    materialTags: ["grid", "partition"],
    areaSqft: 600,
    materials: "Grid ceiling, glass partitions",
    timeline: "6 days",
    costRangeMin: 80000,
    costRangeMax: 120000,
    challenge: "Client needed the office ceiling and partitions done over a weekend to avoid closing during business days.",
    solution: "Scheduled the full crew across a weekend, delivering a finished commercial-grade ceiling and partition layout by Monday.",
    beforeImage: "/images/gallery-29.jpg",
    afterImage: "/images/gallery-30.jpg",
    images: ["/images/gallery-30.jpg", "/images/gallery-31.jpg"],
    customerName: "Deepak Gupta",
    customerReview: "Complete office का काम JK Interior को दिया। On-time delivery और zero hidden charges।",
    customerRating: 5,
    displayOrder: 4,
  },
  {
    slug: "raniganj-bedroom-uv-marble",
    title: "Raniganj Bedroom — UV Marble Sheet Feature Wall",
    serviceSlug: "uv-marble-sheet",
    citySlug: "raniganj",
    spaceType: "residential" as const,
    materialTags: ["uv-marble"],
    areaSqft: 100,
    materials: "UV marble sheets",
    timeline: "1 day",
    costRangeMin: 8000,
    costRangeMax: 14000,
    challenge: "Client wanted a marble look for a feature wall without the weight and cost of real stone.",
    solution: "Installed high-gloss UV marble sheets with dust-free fixing, completed in a single day.",
    beforeImage: "/images/gallery-3.jpg",
    afterImage: "/images/uv-marble.jpg",
    images: ["/images/uv-marble.jpg"],
    customerName: "Sunita Devi",
    customerReview: "UV marble sheet लगवाई पूरे bedroom में। Marble जैसा ही look आया but cost बहुत कम था।",
    customerRating: 5,
    displayOrder: 5,
  },
  {
    slug: "jogbani-shop-pvc-ceiling",
    title: "Jogbani Shop — PVC Ceiling & ACP Frontage",
    serviceSlug: "acp-exterior",
    citySlug: "jogbani",
    spaceType: "commercial" as const,
    materialTags: ["acp", "pvc"],
    areaSqft: 320,
    materials: "ACP sheets, PVC interior ceiling",
    timeline: "5 days",
    costRangeMin: 60000,
    costRangeMax: 90000,
    challenge: "Border-town shopfront needed a weatherproof, eye-catching frontage plus a durable interior ceiling.",
    solution: "Fitted ACP cladding on the frontage and a matching PVC ceiling inside for a consistent, low-maintenance finish.",
    beforeImage: "/images/gallery-4.jpg",
    afterImage: "/images/gallery-31.jpg",
    images: ["/images/gallery-31.jpg", "/images/pvc-ceiling.jpg"],
    customerName: "Meena Yadav",
    customerReview: "Free site visit के लिए आए, detailed quotation दिया, और काम शुरू किया। हर step professional था।",
    customerRating: 5,
    displayOrder: 6,
  },
];

export const galleryItemsSeed: { projectSlug: string; imageUrl: string; altText: string; materialTag: string; spaceType: string; displayOrder: number }[] = [
  { projectSlug: "forbesganj-living-room-pvc-ceiling", imageUrl: "/images/pvc-ceiling.jpg", altText: "PVC false ceiling with cove lighting in Forbesganj living room", materialTag: "pvc", spaceType: "residential", displayOrder: 1 },
  { projectSlug: "forbesganj-living-room-pvc-ceiling", imageUrl: "/images/pvc1.jpg", altText: "PVC ceiling panel detail", materialTag: "pvc", spaceType: "residential", displayOrder: 2 },
  { projectSlug: "araria-bedroom-gypsum-ceiling", imageUrl: "/images/gypsum-ceiling.jpg", altText: "Gypsum false ceiling with POP cornice in Araria bedroom", materialTag: "gypsum", spaceType: "residential", displayOrder: 1 },
  { projectSlug: "araria-bedroom-gypsum-ceiling", imageUrl: "/images/gypsum1.jpg", altText: "Gypsum ceiling cove lighting detail", materialTag: "gypsum", spaceType: "residential", displayOrder: 2 },
  { projectSlug: "purnia-tv-unit-wpc-panel", imageUrl: "/images/wpc-louvers.jpg", altText: "WPC louver wall panel behind TV unit in Purnia", materialTag: "wpc", spaceType: "residential", displayOrder: 1 },
  { projectSlug: "purnia-tv-unit-wpc-panel", imageUrl: "/images/tv-unit.jpg", altText: "Custom modular TV unit in Purnia living room", materialTag: "tv-unit", spaceType: "residential", displayOrder: 2 },
  { projectSlug: "supaul-office-grid-ceiling", imageUrl: "/images/gallery-30.jpg", altText: "Grid false ceiling in Supaul office", materialTag: "grid", spaceType: "office", displayOrder: 1 },
  { projectSlug: "supaul-office-grid-ceiling", imageUrl: "/images/gallery-31.jpg", altText: "Office partition wall in Supaul", materialTag: "partition", spaceType: "office", displayOrder: 2 },
  { projectSlug: "raniganj-bedroom-uv-marble", imageUrl: "/images/uv-marble.jpg", altText: "UV marble sheet feature wall in Raniganj bedroom", materialTag: "uv-marble", spaceType: "residential", displayOrder: 1 },
  { projectSlug: "jogbani-shop-pvc-ceiling", imageUrl: "/images/gallery-31.jpg", altText: "ACP cladding shop frontage in Jogbani", materialTag: "acp", spaceType: "commercial", displayOrder: 1 },
];

export const reviewsSeed = [
  { authorName: "Rahul Kumar", rating: 5, text: "JK Interior ने हमारे घर का PVC false ceiling बेहद खूबसूरती से लगाया। पूरे Forbesganj में best interior work!", citySlug: "forbesganj" },
  { authorName: "Priya Sharma", rating: 5, text: "Gypsum ceiling के लिए JK Interior को hire किया। Professional team, clean work, और 1 साल की warranty।", citySlug: "araria-city" },
  { authorName: "Amit Singh", rating: 5, text: "WPC wall paneling का काम बहुत अच्छा किया। Forbesganj का सबसे trusted interior contractor!", citySlug: "forbesganj" },
  { authorName: "Sunita Devi", rating: 5, text: "UV marble sheet लगवाई पूरे bedroom में। Dust-free installation और quick delivery।", citySlug: "raniganj" },
  { authorName: "Deepak Gupta", rating: 5, text: "Complete home interior का काम JK Interior को दिया। On-time delivery और zero hidden charges। Bihar का best interior designer!", districtSlug: "supaul" },
  { authorName: "Meena Yadav", rating: 5, text: "Free site visit के लिए आए, detailed quotation दिया, और काम शुरू किया। Raniganj में JK Interior best है!", citySlug: "raniganj" },
];

export const faqsSeed = [
  { question: "How much does a false ceiling cost per sq.ft?", answer: "PVC false ceiling starts around ₹70–₹140/sq.ft and gypsum false ceiling around ₹80–₹150/sq.ft depending on design and lighting. Use our Price Calculator for a room-specific estimate.", category: "pricing" as const, displayOrder: 1 },
  { question: "Do you provide a free site visit?", answer: "Yes — JK Interior provides a free expert site visit across all our service areas to take exact measurements and share a detailed quotation.", category: "general" as const, displayOrder: 2 },
  { question: "How long does installation take?", answer: "A standard room's false ceiling is usually completed in 1–3 days. Larger or multi-room projects get a detailed timeline shared upfront.", category: "general" as const, displayOrder: 3 },
  { question: "Do you offer a warranty?", answer: "Yes, all JK Interior projects come with a 1-year written warranty covering workmanship.", category: "general" as const, displayOrder: 4 },
  { question: "Which areas does JK Interior serve?", answer: "We serve Araria, Purnia, Supaul, Katihar, Madhepura and Kishanganj districts. See our Areas We Serve page for the full list of cities.", category: "district" as const, displayOrder: 5 },
];

export const blogPostsSeed = [
  {
    slug: "pvc-vs-gypsum-false-ceiling-which-is-better",
    title: "PVC vs Gypsum False Ceiling: Which Is Better for Your Home?",
    excerpt: "A side-by-side comparison of cost, waterproofing, and design flexibility to help you choose the right false ceiling material.",
    content:
      "Both PVC and gypsum false ceilings are popular in Bihar homes, but they suit different rooms. PVC is 100% waterproof and termite-proof, making it ideal for kitchens and bathrooms, while gypsum gives a smoother, paintable finish better suited to living rooms and bedrooms where multi-level cove lighting designs are wanted. Cost-wise, both start in a similar ₹70-150/sq.ft range depending on design complexity. Use our price calculator to get a room-specific estimate, or read our PVC and Gypsum service pages for full material and installation details.",
    coverImage: "/images/pvc-ceiling.jpg",
    serviceSlugs: ["pvc-false-ceiling", "gypsum-false-ceiling"],
    districtSlug: "araria",
  },
  {
    slug: "false-ceiling-cost-guide-bihar-2026",
    title: "False Ceiling Cost Guide for Bihar Homes (2026)",
    excerpt: "Typical price ranges per sq.ft for PVC, gypsum, and WPC false ceiling work across our service districts.",
    content:
      "False ceiling costs vary by material and design complexity. PVC ceilings typically run ₹70-140/sq.ft, gypsum ₹80-150/sq.ft, and WPC wall panels ₹180-450/sq.ft depending on the finish. Distance from our Forbesganj base can add a small site-visit cost for further districts like Katihar, Madhepura and Kishanganj. The best way to get an accurate number for your room is our free site visit or the price calculator tool.",
    coverImage: "/images/gypsum-ceiling.jpg",
    serviceSlugs: ["pvc-false-ceiling", "gypsum-false-ceiling", "wpc-wall-panel"],
    districtSlug: "purnia",
  },
  {
    slug: "wpc-wall-panels-trending-accent-wall-designs",
    title: "5 Trending WPC Wall Panel Designs for Accent Walls",
    excerpt: "From fluted textures to charcoal finishes, here are the wall panel looks our clients are requesting most in 2026.",
    content:
      "WPC wall panels have become the go-to choice for TV accent walls and bedroom headboard walls because they combine a wood-look finish with full moisture resistance. Fluted and louver textures are the most requested designs this year, followed by matte charcoal panels for a bolder, contemporary look. See our WPC Wall Panel and Louvers Panel service pages for material details and pricing.",
    coverImage: "/images/wpc-louvers.jpg",
    serviceSlugs: ["wpc-wall-panel", "louvers-panel", "charcoal-panel"],
    districtSlug: "supaul",
  },
];
