export const galleryImages = [
  { src: "/images/hero-interior.jpg", alt: "Luxury living room interior design Bihar" },
  { src: "/images/gypsum-ceiling.jpg", alt: "Gypsum false ceiling design Patna" },
  { src: "/images/pvc-ceiling.jpg", alt: "PVC ceiling installation Lauriya" },
  { src: "/images/wpc-louvers.jpg", alt: "WPC louvers wall panel Bihar" },
  { src: "/images/tv-unit.jpg", alt: "Modern TV unit design Patna" },
  { src: "/images/gallery-1.jpg", alt: "Designer bedroom interior Bettiah" },
  { src: "/images/gallery-2.jpg", alt: "Modular kitchen interior Bihar" },
  { src: "/images/gallery-3.jpg", alt: "Professional office interior Patna" },
  { src: "/images/gallery-4.jpg", alt: "Luxury drawing room false ceiling" },
  { src: "/images/fluted-panels.jpg", alt: "Fluted wall panels TV unit" },
  { src: "/images/uv-marble.jpg", alt: "UV marble sheet wall design" },
  { src: "/images/artificial-grass.jpg", alt: "Artificial grass balcony decoration" },
  { src: "/images/gallery-5.jpg", alt: "Gypsum ceiling design for bedroom Lauriya" },
  { src: "/images/gallery-6.jpg", alt: "PVC ceiling panels modern home Bihar" },
  { src: "/images/gallery-7.jpg", alt: "WPC louvers living room wall design" },
  { src: "/images/gallery-8.jpg", alt: "Luxury TV unit with LED panel Patna" },
  { src: "/images/gallery-9.jpg", alt: "Modular kitchen interior design Bihar" },
  { src: "/images/gallery-10.jpg", alt: "Office false ceiling gypsum work" },
  { src: "/images/gallery-11.jpg", alt: "Fluted panels bedroom headboard design" },
  { src: "/images/gallery-12.jpg", alt: "UV marble sheet TV wall Lauriya" },
  { src: "/images/gallery-13.jpg", alt: "Artificial grass balcony decoration" },
  { src: "/images/gallery-14.jpg", alt: "Designer drawing room ceiling" },
  { src: "/images/gallery-15.jpg", alt: "PVC wall paneling for shop" },
  { src: "/images/gallery-16.jpg", alt: "WPC ceiling outdoor area" },
  { src: "/images/gallery-17.jpg", alt: "Gypsum partition wall design" },
  { src: "/images/gallery-18.jpg", alt: "Modern bedroom interior Bihar" },
  { src: "/images/gallery-19.jpg", alt: "Luxury kitchen with island" },
  { src: "/images/gallery-20.jpg", alt: "Office cabin interior design" },
  { src: "/images/gallery-21.jpg", alt: "Living room false ceiling with cove light" },
  { src: "/images/gallery-22.jpg", alt: "PVC louvers exterior design" },
  { src: "/images/gallery-23.jpg", alt: "TV cabinet with fluted panels" },
  { src: "/images/gallery-24.jpg", alt: "Restaurant interior ceiling work" },
  { src: "/images/gallery-25.jpg", alt: "Bedroom PVC ceiling design" },
  { src: "/images/gallery-26.jpg", alt: "Hall gypsum design Lauriya Nandangarh" },
  { src: "/images/gallery-27.jpg", alt: "WPC deck flooring balcony" },
  { src: "/images/gallery-28.jpg", alt: "Modular wardrobe design" },
  { src: "/images/gallery-29.jpg", alt: "UV board kitchen shutters" },
  { src: "/images/gallery-30.jpg", alt: "False ceiling for shop Bihar" },
  { src: "/images/gallery-31.jpg", alt: "3D wall panel living room" },
  { src: "/images/gallery-32.jpg", alt: "Gypsum ceiling with fan design" },
  { src: "/images/gallery-33.jpg", alt: "PVC ceiling bathroom waterproof" },
  { src: "/images/gallery-34.jpg", alt: "Office reception interior" },
  { src: "/images/gallery-35.jpg", alt: "Bedroom wall WPC louvers" },
  { src: "/images/gallery-36.jpg", alt: "TV unit with marble finish" },
  { src: "/images/gallery-37.jpg", alt: "Kitchen ceiling PVC panels" },
  { src: "/images/gallery-38.jpg", alt: "Living room interior Lauriya" },
  { src: "/images/gallery-39.jpg", alt: "Gypsum arch design" },
  { src: "/images/gallery-40.jpg", alt: "Fluted panel pooja room" },
  { src: "/images/gallery-41.jpg", alt: "Artificial grass wall decor" },
  { src: "/images/gallery-42.jpg", alt: "Complete home interior Bihar" },
]

export function buildGalleryJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "ImageGallery",
    name: "Interior Design & False Ceiling Projects - Bihar Patna",
    description:
      "Portfolio of false ceiling, PVC panels, WPC louvers, TV unit, modular kitchen and bedroom interior design projects in Bihar and Patna.",
    image: galleryImages.map((img) => `https://www.jkinterior.online${img.src}`),
  }
}
